{% set name = "PyFMI" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  md5: bcbc480b56e7dd86b8d17918ead207d2
  patches:
    # https://github.com/cython/cython/issues/1518
    - fix-omp-include.patch

    # fix key error in get_temp_location when USER not in env
    # http://trac.jmodelica.org/changeset/9706
    - get_temp_location-keyerror.patch

build:
  number: 1003

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - fmilib
    - numpy
    - cython
  run:
    - python
    - fmilib
    - {{ pin_compatible('numpy') }}
    - scipy
    - lxml
    - assimulo

test:
  imports:
    - pyfmi
    - pyfmi.common
    - pyfmi.common.plotting
    - pyfmi.examples
    - pyfmi.simulation
  requires:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]

about:
  home: http://www.jmodelica.org/
  license: LGPL3
  license_file: LICENSE
  summary: PyFMI is a package for loading and interacting with Functional Mock-Up Units

extra:
  recipe-maintainers:
    - jschueller
    - chria
