{% set name = "PyFMI" %}
{% set version = "2.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/modelon-community/PyFMI/archive/PyFMI-{{ version }}.tar.gz
  sha256: bb91c99a6431ddf22500073fb7e6965fec098d5e10c699db820bcd58772c3683

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - fmilib
    - numpy
    - cython
    - assimulo >=3.0
  run:
    - python
    - fmilib
    - {{ pin_compatible('numpy') }}
    - scipy
    - lxml
    - assimulo >=3.0

test:
  imports:
    - pyfmi
    - pyfmi.common
    - pyfmi.common.plotting
    - pyfmi.examples
    - pyfmi.simulation

about:
  home: http://www.jmodelica.org/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: PyFMI is a package for loading and interacting with Functional Mock-Up Units

extra:
  recipe-maintainers:
    - jschueller
    - chria
