{% set name = "PyFMI" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  md5: bcbc480b56e7dd86b8d17918ead207d2
  patches:
    # https://github.com/cython/cython/issues/1518
    - fix-omp-include.patch
    # fix key error in get_temp_location when USER not in env
    # http://trac.jmodelica.org/changeset/9706
    - get_temp_location-keyerror.patch

build:
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]
  number: 2

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - fmilib
    - numpy 1.9.*  # [not (win and py36)]
    - numpy 1.11.*  # [win and py36]
    - cython
  run:
    - python
    - fmilib
    - numpy >=1.9  # [not (win and py36)]
    - numpy >=1.11  # [win and py36]
    - scipy
    - lxml
    - assimulo

test:
  imports:
    - pyfmi
    - pyfmi.common
    - pyfmi.common.plotting
    - pyfmi.examples
    - pyfmi.simulation

about:
  home: http://www.jmodelica.org/
  license: LGPL3
  license_file: LICENSE
  summary: PyFMI is a package for loading and interacting with Functional Mock-Up Units

extra:
  recipe-maintainers:
    - jschueller
    - chria
