{% set name = "PyFMI" %}
{% set version = "2.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/modelon-community/PyFMI/archive/PyFMI-{{ version }}.tar.gz
  sha256: a95b5571428917945965f1cfad1c504c747e7be2a800435480dc205de659c351
  patches:
    # https://github.com/modelon-community/PyFMI/pull/78
    - me_param.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - fmilib
    - numpy
    - cython
    - assimulo >=3.0
  run:
    - python
    - fmilib
    - {{ pin_compatible('numpy') }}
    - scipy
    - lxml
    - assimulo >=3.0

test:
  imports:
    - pyfmi
    - pyfmi.common
    - pyfmi.common.plotting
    - pyfmi.examples
    - pyfmi.simulation

about:
  home: http://www.jmodelica.org/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: PyFMI is a package for loading and interacting with Functional Mock-Up Units

extra:
  recipe-maintainers:
    - jschueller
    - chria
