{% set name = "PyFMI" %}
{% set version = "2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/modelon/PyFMI/archive/PyFMI-{{ version }}.tar.gz
  sha256: a198707e6af69c2d3b6cb5ef4361875dd964542b1650204e3262052ee9f167ff
  patches:
    # https://github.com/cython/cython/issues/1518
    - fix-omp-include.patch
    # https://github.com/modelon/PyFMI/issues/10
    - encoding.patch
    # https://github.com/modelon/PyFMI/issues/12
    - logging.patch

build:
  number: 1005

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - fmilib
    - numpy
    - cython
  run:
    - python
    - fmilib
    - {{ pin_compatible('numpy') }}
    - scipy
    - lxml
    - assimulo >=3.0

test:
  imports:
    - pyfmi
    - pyfmi.common
    - pyfmi.common.plotting
    - pyfmi.examples
    - pyfmi.simulation

about:
  home: http://www.jmodelica.org/
  license: LGPL
  license_file: LICENSE
  summary: PyFMI is a package for loading and interacting with Functional Mock-Up Units

extra:
  recipe-maintainers:
    - jschueller
    - chria
