appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: moV4nqn/lQqxZy5SoAeGlxF7pn94YGizzXpr+N6ccZgOtLP5ZpjvbsPSO8g28NcqAciRStS9NniBmWGI4v9/3EPf29OW2DEhQLoH2cMTM0pisb8ojV1H5Fr6unoP0HdbbWppuFyzsXyTS8yQ3B0P+RGnPTvJF9MMWA33eqbrJnnuszz5D0RripjDddnoepSv9HhDMPuugr6oj3Al7nRhVWCRiWQSUxyRd6y+K+PVJUdAQEPKHJnMsRgBFLWg3lkA9hvbWni3tejUDNeBH2XsMa9nZQPkn/upT+TT1Cu+zEH8ZOXcZURPmoTRTXggLDbMPHR0Louq8B5RD+p1TR6Kmlinn/uPq6NbCOqk2hejtyIh9yFC1X2o7ynEv8h8M+WKjr4D+2JffETefdzVNpu+vU1amm7klUUKEYrnxd3JX1Rza3Gu+v0/ynIFW4gZJGnffs03fF0hz8u/vzo1mZQZ+lg+tmuZ8gVpAw4ukO38GdP2W/RilbWxZwJgVWa2+6IkEudpf4iyuDTbrAR7lU/h2URepl/jLknNR8LsxoSYVM3XUvFc2+8phCH3Mf8jap0xlzrmijrNLVrpunDaaRgt90rhiTH20la6Je8BE1F2gtDQCTXr+FERVGRExJnCtdvB+aCWzfAo6KEIlYCWDTOXe9aFVh8D5gE9W/k931KvPQo=}
provider:
  win: azure
conda_forge_output_validation: true
