travis:
  secure:
    BINSTAR_TOKEN: ZxL3Z8RZRNSmdMsokPJQ4+obj3S5/0p5ZwrN8usxv5KBUBAOjy4OVrhUc3/8CVyFQ7MQnFznBowXlKfl3mKlgUk1WB+qyuoqmN4A0b8F5CGaETxjv8lUHQejX7OEw3kbKTirJ+T20axVbM+CBbpio/RH3XK7LiiW4jCh0HrY/jfx3PBEgWu5XQGr9mjkQ0rJOGxalHn8WCQSh6AaFHypj/d1FNKPDH1mG5Zmr/Aac7BoVAl3Qdqu2+7k9wK9xMFk0ikLteumWWwjy9H3AbaMUgQXOQa1BkeQxSt+BbuG2QLApvklzuBI9TGm4DeLd5kQH+A6sJfMoHZzSbBNIOAnDlC/Gft58Il2FKF3Eruul/Hrq6qD2O/LErXpIaXVs0E6M3TG9pMqrmZLMLCXBGevFLi4s+soA3mm2zTyAHPXMTiOCtnxp7BBSZ820svF/UkgMw68vIwEk8QvU6LkfjnxNX3Xz17XwAcUsLW7qIShJ+YqFxPfcgwAEOKLYqYvtNP1z575asrKlBH87f74ElRSWhgY5fqssKLpCGOKuQ1a1TlaTrX99p1wtO4i8t3YrsuCAXje7d+bf7KNdcaaBhQJk2i7/HvpRhMDI5ebOmgVoDOI3F4Q6sY1WY92aEwF5Sh9GmMXla9Pwopuxdh537L9aiXGIc2vZ+x4vPXoOwQ5a+E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
